# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created: Tue Nov 06 14:20:47 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName(_fromUtf8("MainForm"))
        MainForm.resize(660, 220)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainForm.sizePolicy().hasHeightForWidth())
        MainForm.setSizePolicy(sizePolicy)
        MainForm.setMinimumSize(QtCore.QSize(660, 220))
        MainForm.setMaximumSize(QtCore.QSize(660, 220))
        self.layoutWidget = QtGui.QWidget(MainForm)
        self.layoutWidget.setGeometry(QtCore.QRect(510, 20, 159, 181))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.showTimeFromGo = QtGui.QLabel(self.layoutWidget)
        self.showTimeFromGo.setMinimumSize(QtCore.QSize(80, 30))
        self.showTimeFromGo.setFrameShape(QtGui.QFrame.Panel)
        self.showTimeFromGo.setLineWidth(3)
        self.showTimeFromGo.setMidLineWidth(2)
        self.showTimeFromGo.setText(_fromUtf8(""))
        self.showTimeFromGo.setObjectName(_fromUtf8("showTimeFromGo"))
        self.horizontalLayout_2.addWidget(self.showTimeFromGo)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.showTimeFromStart = QtGui.QLabel(self.layoutWidget)
        self.showTimeFromStart.setMinimumSize(QtCore.QSize(80, 30))
        self.showTimeFromStart.setFrameShape(QtGui.QFrame.Panel)
        self.showTimeFromStart.setLineWidth(3)
        self.showTimeFromStart.setMidLineWidth(2)
        self.showTimeFromStart.setText(_fromUtf8(""))
        self.showTimeFromStart.setObjectName(_fromUtf8("showTimeFromStart"))
        self.horizontalLayout_3.addWidget(self.showTimeFromStart)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_3.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.splitter = QtGui.QSplitter(MainForm)
        self.splitter.setGeometry(QtCore.QRect(10, 15, 473, 181))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(30)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.displayRecurso = QtGui.QLabel(self.layoutWidget1)
        self.displayRecurso.setMinimumSize(QtCore.QSize(292, 20))
        self.displayRecurso.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayRecurso.setFrameShadow(QtGui.QFrame.Raised)
        self.displayRecurso.setMidLineWidth(1)
        self.displayRecurso.setText(_fromUtf8(""))
        self.displayRecurso.setObjectName(_fromUtf8("displayRecurso"))
        self.gridLayout.addWidget(self.displayRecurso, 0, 1, 1, 1)
        self.setRecursoButton = QtGui.QPushButton(self.layoutWidget1)
        self.setRecursoButton.setMinimumSize(QtCore.QSize(96, 0))
        self.setRecursoButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setRecursoButton.setObjectName(_fromUtf8("setRecursoButton"))
        self.gridLayout.addWidget(self.setRecursoButton, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.displayProyecto = QtGui.QLabel(self.layoutWidget1)
        self.displayProyecto.setMinimumSize(QtCore.QSize(292, 20))
        self.displayProyecto.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayProyecto.setFrameShadow(QtGui.QFrame.Raised)
        self.displayProyecto.setText(_fromUtf8(""))
        self.displayProyecto.setObjectName(_fromUtf8("displayProyecto"))
        self.gridLayout.addWidget(self.displayProyecto, 1, 1, 1, 1)
        self.setProyectoButton = QtGui.QPushButton(self.layoutWidget1)
        self.setProyectoButton.setMinimumSize(QtCore.QSize(96, 0))
        self.setProyectoButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setProyectoButton.setObjectName(_fromUtf8("setProyectoButton"))
        self.gridLayout.addWidget(self.setProyectoButton, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.displayTarea = QtGui.QLabel(self.layoutWidget1)
        self.displayTarea.setMinimumSize(QtCore.QSize(292, 20))
        self.displayTarea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayTarea.setFrameShadow(QtGui.QFrame.Raised)
        self.displayTarea.setText(_fromUtf8(""))
        self.displayTarea.setObjectName(_fromUtf8("displayTarea"))
        self.gridLayout.addWidget(self.displayTarea, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.displayActividad = QtGui.QLabel(self.layoutWidget1)
        self.displayActividad.setMinimumSize(QtCore.QSize(292, 20))
        self.displayActividad.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayActividad.setFrameShadow(QtGui.QFrame.Raised)
        self.displayActividad.setText(_fromUtf8(""))
        self.displayActividad.setObjectName(_fromUtf8("displayActividad"))
        self.gridLayout.addWidget(self.displayActividad, 3, 1, 1, 1)
        self.setActividadButton = QtGui.QPushButton(self.layoutWidget1)
        self.setActividadButton.setMinimumSize(QtCore.QSize(96, 0))
        self.setActividadButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setActividadButton.setObjectName(_fromUtf8("setActividadButton"))
        self.gridLayout.addWidget(self.setActividadButton, 3, 2, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.goButton = QtGui.QPushButton(self.layoutWidget2)
        self.goButton.setMinimumSize(QtCore.QSize(96, 0))
        self.goButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.goButton.setObjectName(_fromUtf8("goButton"))
        self.horizontalLayout.addWidget(self.goButton)
        self.stopButton = QtGui.QPushButton(self.layoutWidget2)
        self.stopButton.setMinimumSize(QtCore.QSize(96, 0))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout.addWidget(self.stopButton)
        spacerItem1 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.exitButton = QtGui.QPushButton(self.layoutWidget2)
        self.exitButton.setMinimumSize(QtCore.QSize(96, 0))
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.horizontalLayout.addWidget(self.exitButton)

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)
        MainForm.setTabOrder(self.goButton, self.stopButton)
        MainForm.setTabOrder(self.stopButton, self.exitButton)

    def retranslateUi(self, MainForm):
        MainForm.setWindowTitle(QtGui.QApplication.translate("MainForm", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainForm", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">From Go:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainForm", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainForm", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">From Start:</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainForm", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainForm", "Nombre:", None, QtGui.QApplication.UnicodeUTF8))
        self.setRecursoButton.setText(QtGui.QApplication.translate("MainForm", "Recurso", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainForm", "Proyecto:", None, QtGui.QApplication.UnicodeUTF8))
        self.setProyectoButton.setText(QtGui.QApplication.translate("MainForm", "Proyecto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainForm", "Tarea:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainForm", "Actividad:", None, QtGui.QApplication.UnicodeUTF8))
        self.setActividadButton.setText(QtGui.QApplication.translate("MainForm", "Actividad", None, QtGui.QApplication.UnicodeUTF8))
        self.goButton.setText(QtGui.QApplication.translate("MainForm", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainForm", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.exitButton.setText(QtGui.QApplication.translate("MainForm", "Exit", None, QtGui.QApplication.UnicodeUTF8))

